const $ = (s) => document.querySelector(s); let rides = []; let config;
const saved = (key) => { const value = document.cookie.split('; ').find(row => row.startsWith(`${key}=`)); return value ? decodeURIComponent(value.split('=')[1]) : ''; };
function remember(form) { ['name','email'].forEach(key => { const value = form.elements[key]?.value; if (value) document.cookie = `${key}=${encodeURIComponent(value)}; max-age=${60*60*24*30}; path=/; SameSite=Lax`; }); }
function showMessage(text, error = false) { const box = $('#message'); box.textContent = text; box.className = `message${error ? ' error' : ''}`; box.hidden = false; setTimeout(() => box.hidden = true, 4000); }
function escape(value) { return String(value).replace(/[&<>\"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[character])); }
function render() { $('#rideCount').textContent = `${rides.length} ride${rides.length === 1 ? '' : 's'}`; const grouped = config.dates.map(date => ({ date, rides: rides.filter(r => r.date === date) })).flatMap(x => x.rides.map(ride => ({...ride, dateLabel:config.labels[x.date]}))); $('#rides').innerHTML = grouped.length ? grouped.map(ride => `<article class="ride"><div><div class="ride-date">${escape(ride.dateLabel)} <span class="ride-meta">at ${ride.time}</span></div><div class="ride-meta"><b>${ride.intensity}</b> intensity &nbsp;•&nbsp; <b>${ride.length}</b> ride</div><div class="avatars">${ride.participants.map(p => `<span class="avatar" title="${escape(p.name)}">${escape(p.name.slice(0,1).toUpperCase())}</span>`).join('')}<span class="ride-meta" style="margin-left:10px">${ride.participants.length} rider${ride.participants.length===1?'':'s'}</span></div></div><div><button class="join" data-join="${ride.id}">Join ride</button><button class="leave" data-leave="${ride.id}">Leave</button></div></article>`).join('') : '<div class="empty">No rides planned yet. Be the first to start one.</div>'; }
async function load() { const [c, r] = await Promise.all([fetch('/api/config'), fetch('/api/rides')]); config = await c.json(); rides = await r.json(); $('#date').innerHTML = config.dates.map((d,i) => `<option value="${d}">${i===0?'Today — ':''}${config.labels[d]}</option>`).join(''); render(); }
$('#createForm').addEventListener('submit', async (e) => { e.preventDefault(); const form = e.currentTarget; remember(form); const data = Object.fromEntries(new FormData(form)); const response = await fetch('/api/rides',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const result = await response.json(); if (!response.ok) return showMessage(result.error,true); form.reset(); showMessage('Ride created — invite your friends.'); await load(); });
$('#rides').addEventListener('click', async (e) => { const join = e.target.closest('[data-join]'); const leave = e.target.closest('[data-leave]'); if (join) { $('#joinForm').elements.rideId.value = join.dataset.join; const ride = rides.find(r=>r.id===join.dataset.join); $('#joinTitle').textContent = `Join ${config.labels[ride.date]}`; $('#joinForm').elements.name.value=saved('name'); $('#joinForm').elements.email.value=saved('email'); $('#joinDialog').showModal(); } if (leave) { const email = prompt('Enter the e-mail you used to join this ride:'); if (!email) return; const response = await fetch(`/api/rides/${leave.dataset.leave}/leave`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}); const result=await response.json(); if(!response.ok)return showMessage(result.error,true); showMessage('You have left the ride.'); await load(); } });
$('#joinForm').addEventListener('submit', async (e) => { e.preventDefault(); const form=e.currentTarget; remember(form); const data=Object.fromEntries(new FormData(form)); const id=data.rideId; delete data.rideId; const response=await fetch(`/api/rides/${id}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const result=await response.json(); $('#joinDialog').close(); if(!response.ok)return showMessage(result.error,true); showMessage('You are on the ride list.'); await load(); });
load().catch(()=>showMessage('Could not connect to the server.',true));
